# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Implement a random walk Metropolis sampler.
#' @description Implement a random walk Metropolis sampler for generating the standard Laplace distribution
#' @param sigma the standard deviation of a normal distribution
#' @param x0 the initial value of a random walk sequence
#' @param N the length of a random walk sequence
#' @return  a random walk Metropolis sequence and number of candidate points rejected \code{n}
#' @examples
#' \dontrun{
#' set.seed(1234)
#' N = 2000
#' sigma = 1
#' x0 = 25
#' rw = rwc(sigma,x0,N)
#' }
#' @useDynLib StatComp20040
#' @export
rwc <- function(sigma, x0, N) {
    .Call('_StatComp20040_rwc', PACKAGE = 'StatComp20040', sigma, x0, N)
}

